apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: speech
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SiluniLabs/cluster-synced.git
    targetRevision: main
    path: apps/speech
  destination:
    server: https://kubernetes.default.svc
    namespace: speech
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
